// Holds c64o/planes.cc to its reference, lib/planes.py, byte for byte.
//
// planes_cases.h is generated by tools/generate_planes.py --cases: camera-space
// inputs, and the FNV-1a hash of what lib/planes.py renders from them -- the
// level, Y-expansion, layout, origin, slide, clamp and every bitmap byte --
// and whether its vertex cache hit. The stateless cases start from a fresh
// state each; the approaches carry one through the hysteresis and the vertex
// cache, and the drifts through frames that planes.cc need not project. This
// renders each the way a C64 program would, with a front and a back buffer,
// and compares hashes and cache hits: a miss where the reference hits would
// redraw the same bitmap, and no hash would show it.
//
// vec_fastmul8p8 is the host stand-in from vec.h, which host_vec.cc (in the
// flight suite) checks against the 6502 routine.

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <string>

#include "../planes.h"
#include "planes_cases.h"

static uint32_t fnv1a(const std::string &s) {
  uint32_t h = 0x811C9DC5u;
  for (unsigned char ch : s) {
    h = (h ^ ch) * 0x01000193u;
  }
  return h;
}

static void hex(std::string &out, const uint8_t *bytes, int n) {
  static const char kDigits[] = "0123456789abcdef";
  for (int i = 0; i < n; ++i) {
    out += kDigits[bytes[i] >> 4];
    out += kDigits[bytes[i] & 15];
  }
}

int main() {
  const planes_view_t view = {kCaseCx0, kCaseCy0, kCaseCut1, kCaseCut2};
  static const char *const kReasons[] = {"", "behind camera", "out of range",
                                         "below the sprite cut"};
  static uint8_t sets[2][4][kPlaneBlockStride];
  uint8_t dot[kPlaneBlockBytes];
  planes_dot_bitmap(dot);

  planes_state_t state;
  planes_state_init(&state);
  int front = 0;
  int fails = 0, cached = 0;
  const int count = (int)(sizeof(kPlaneCases) / sizeof(kPlaneCases[0]));

  for (int n = 0; n < count; ++n) {
    const plane_case_t &pc = kPlaneCases[n];
    if (pc.fresh) {
      planes_state_init(&state);
    }
    vec3_t c = make_vector(pc.c[0], pc.c[1], pc.c[2]);
    mat3_t axes;
    axes.front = make_vector(pc.axes[0][0], pc.axes[0][1], pc.axes[0][2]);
    axes.left = make_vector(pc.axes[1][0], pc.axes[1][1], pc.axes[1][2]);
    axes.up = make_vector(pc.axes[2][0], pc.axes[2][1], pc.axes[2][2]);
    uint8_t *back = sets[front ^ 1][0];

    planes_frame_t frame;
    planes_render(&state, &view, &c, &axes, back, &frame);

    std::string sig;
    if (frame.hidden != kPlaneShown) {
      sig = std::string("invisible:") + kReasons[frame.hidden];
    } else {
      char head[64];
      snprintf(head, sizeof(head), "%d|%d|%dx%d|%d,%d|%d|%d|", frame.level, frame.ys,
               frame.cols, frame.rows, frame.x, frame.y, frame.slid, frame.clamped ? 1 : 0);
      sig = head;
      if (frame.level == kPlaneLevelDot) {
        hex(sig, dot, kPlaneBlockBytes);
      } else {
        if (frame.cached) {
          ++cached;
        } else {
          front ^= 1;
        }
        for (int b = 0; b < frame.cols * frame.rows; ++b) {
          hex(sig, sets[front][b], kPlaneBlockBytes);
        }
      }
    }
    if (fnv1a(sig) != pc.hash) {
      if (++fails <= 5) {
        printf("planes_test: case %d differs from lib/planes.py\n  C: %.120s\n", n,
               sig.c_str());
      }
    } else if ((frame.cached ? 1 : 0) != pc.cached) {
      if (++fails <= 5) {
        printf("planes_test: case %d %s the cache where lib/planes.py %s\n", n,
               frame.cached ? "hits" : "misses", pc.cached ? "hits" : "misses");
      }
    }
  }

  if (fails) {
    printf("planes_test: %d of %d cases FAILED\n", fails, count);
    return 1;
  }
  printf("planes_test: %d cases match lib/planes.py byte for byte (%d from the cache)\n",
         count, cached);
  return 0;
}
