# Generated by tools/generate_clouds.py -- do not edit.
# The same constants c64o/clouddef.h carries, for the preview and the tests.
# Hash tables from search seed 77; 20 of 128 cells carry a group.

CELL_U = 2048
CELL_SHIFT = 11
CELLS_X = 8
CELLS_Y = 16
SCAN_RADIUS = 2
GATE_MASK = 7
BLOB_U = 96
DECK_U = 350
OFFSET_U = 48
JITTER_SHIFT = 7
CULL_U = 4096
RUNG_COUNT = 10
RUNG_STACKED = 5
BLOBS_PER_GROUP = 3
PATTERN_COUNT = 4
PROJECTION_SCALE = 128

HASH_X = [129, 166, 101, 123, 98, 58, 149, 243]
HASH_Y = [121, 74, 1, 143, 14, 254, 88, 97, 198, 93, 169, 164, 60, 44, 133, 240]
HASH_A = [104, 115, 98, 36, 41, 102, 224, 39, 51, 108, 168, 44, 48, 236, 40, 54, 139, 227, 62, 179, 28, 206, 126, 112, 241, 206, 70, 196, 6, 17, 26, 253]
HASH_B = [20, 183, 221, 60, 131, 250, 28, 241, 48, 75, 152, 47, 8, 248, 180, 212, 0, 31, 246, 74, 13, 4, 122, 45, 238, 58, 199, 243, 52, 69, 122, 133]
RUNG_DEPTH = [4096, 2458, 1755, 1365, 1117, 945, 819, 723, 647, 585]
GROUP_OFFSET = [[(-2, -1, 0), (2, -1, 0), (0, 2, 1)], [(-1, -2, 0), (-1, 2, 0), (2, 0, 1)], [(-2, 1, 0), (2, 1, 0), (0, -2, 1)], [(1, -2, 0), (1, 2, 0), (-2, 0, 1)]]


def cell_hash(cx, cy):
    """The two hash bytes for a cloud cell. Mirrors _cloud_at() in clouds.cc."""
    a = HASH_X[cx % CELLS_X] ^ HASH_Y[cy % CELLS_Y]
    return HASH_A[a & 31], HASH_B[a & 31]


def group_at(cx, cy):
    """The group in this cell as {pattern, x, y} in world units, or None.

    cx and cy are unmasked cell coordinates, so the position is absolute and
    the hash wraps - exactly how world.cc treats the map.
    """
    ha, hb = cell_hash(cx, cy)
    if (ha & GATE_MASK) != 0:
        return None
    return {
        "pattern": (ha >> 6) & (PATTERN_COUNT - 1),
        "x": cx * CELL_U + ((hb & 0x0F) << JITTER_SHIFT),
        "y": cy * CELL_U + ((hb >> 4) << JITTER_SHIFT),
    }


def rung_for_depth(depth):
    """Ladder rung for a camera-space depth, or None beyond the cull (§3.2)."""
    if depth > RUNG_DEPTH[0]:
        return None
    rung = 0
    while rung < RUNG_COUNT - 1 and depth <= RUNG_DEPTH[rung + 1]:
        rung += 1
    return rung
