# Generated by tools/generate_clouds.py -- do not edit.
# The same constants c64o/clouddef.h carries, for the preview and the tests.
# Hash tables from search seed 34977; 37 of 128 cells carry a group.
# Evenness 0.458 = separation 1741 / covering radius 3799 units (see the
# generator's blue-noise notes). Recorded so the tests can rebuild these
# tables and re-check the layout without repeating the search.

SEARCH_SEED = 34977
EVENNESS = 0.4582
MIN_SEPARATION = 1741.0
COVERING_RADIUS = 3799.3
CELL_U = 2048
CELL_SHIFT = 11
CELLS_X = 8
CELLS_Y = 16
SCAN_RADIUS = 2
GATE_BITS = 31
GATE_LIMIT = 10
BLOB_U = 96
DECK_U = 700
OFFSET_U = 32
JITTER_SHIFT = 7
CULL_U = 4096
RUNG_COUNT = 10
RUNG_STACKED = 5
RUNG_COLLAPSED = 3
BLOBS_PER_GROUP = 3
PATTERN_COUNT = 4
PROJECTION_SCALE = 128

HASH_X = [73, 214, 23, 77, 3, 15, 228, 67]
HASH_Y = [239, 82, 206, 191, 80, 194, 219, 150, 220, 48, 148, 194, 197, 142, 53, 56]
HASH_A = [91, 116, 60, 79, 225, 145, 107, 223, 254, 103, 248, 193, 211, 72, 27, 142, 19, 158, 170, 200, 150, 138, 31, 167, 201, 0, 198, 149, 151, 77, 2, 216]
HASH_B = [146, 162, 166, 127, 85, 130, 44, 210, 35, 79, 107, 66, 170, 74, 147, 44, 195, 197, 133, 161, 186, 173, 252, 199, 135, 137, 186, 251, 90, 254, 28, 202]
RUNG_DEPTH = [4096, 2458, 1755, 1365, 1117, 945, 819, 723, 647, 585]
GROUP_OFFSET = [[(-2, -1, 0), (2, -1, 0), (0, 2, 1)], [(-1, -2, 0), (-1, 2, 0), (2, 0, 1)], [(-2, 1, 0), (2, 1, 0), (0, -2, 1)], [(1, -2, 0), (1, 2, 0), (-2, 0, 1)]]


def cell_hash(cx, cy):
    """The two hash bytes for a cloud cell. Mirrors _cloud_at() in clouds.cc."""
    a = HASH_X[cx % CELLS_X] ^ HASH_Y[cy % CELLS_Y]
    return HASH_A[a & 31], HASH_B[a & 31]


def group_at(cx, cy):
    """The group in this cell as {pattern, x, y} in world units, or None.

    cx and cy are unmasked cell coordinates, so the position is absolute and
    the hash wraps - exactly how world.cc treats the map.
    """
    ha, hb = cell_hash(cx, cy)
    if (ha & GATE_BITS) >= GATE_LIMIT:
        return None
    return {
        "pattern": (ha >> 6) & (PATTERN_COUNT - 1),
        "x": cx * CELL_U + ((hb & 0x0F) << JITTER_SHIFT),
        "y": cy * CELL_U + ((hb >> 4) << JITTER_SHIFT),
    }


def rung_for_depth(depth):
    """Ladder rung for a camera-space depth, or None beyond the cull (§3.2)."""
    if depth > RUNG_DEPTH[0]:
        return None
    rung = 0
    while rung < RUNG_COUNT - 1 and depth <= RUNG_DEPTH[rung + 1]:
        rung += 1
    return rung
