# Generated by tools/generate_clouds.py -- do not edit.
# The same constants c64o/clouddef.h carries, for the preview and the tests.
# Hash tables from search seed 28842; 19 of 128 cells carry a group.
# Evenness 0.577 = separation 2896 / covering radius 5018 units (see the
# generator's blue-noise notes). Recorded so the tests can rebuild these
# tables and re-check the layout without repeating the search.

SEARCH_SEED = 28842
EVENNESS = 0.5772
MIN_SEPARATION = 2896.3
COVERING_RADIUS = 5018.2
CELL_U = 2048
CELL_SHIFT = 11
CELLS_X = 8
CELLS_Y = 16
SCAN_RADIUS = 2
GATE_MASK = 7
BLOB_U = 96
DECK_U = 700
OFFSET_U = 32
JITTER_SHIFT = 7
CULL_U = 4096
RUNG_COUNT = 10
RUNG_STACKED = 5
BLOBS_PER_GROUP = 3
PATTERN_COUNT = 4
PROJECTION_SCALE = 128

HASH_X = [156, 56, 205, 150, 110, 26, 56, 180]
HASH_Y = [97, 240, 92, 212, 35, 135, 233, 175, 14, 223, 24, 29, 17, 246, 232, 86]
HASH_A = [64, 209, 139, 157, 253, 217, 236, 49, 247, 30, 199, 187, 46, 148, 154, 74, 152, 150, 65, 48, 207, 62, 100, 86, 239, 232, 74, 79, 47, 182, 38, 143]
HASH_B = [194, 154, 59, 249, 33, 170, 78, 109, 228, 215, 0, 80, 105, 230, 208, 243, 248, 219, 178, 89, 26, 72, 115, 136, 250, 104, 90, 90, 88, 21, 198, 48]
RUNG_DEPTH = [4096, 2458, 1755, 1365, 1117, 945, 819, 723, 647, 585]
GROUP_OFFSET = [[(-2, -1, 0), (2, -1, 0), (0, 2, 1)], [(-1, -2, 0), (-1, 2, 0), (2, 0, 1)], [(-2, 1, 0), (2, 1, 0), (0, -2, 1)], [(1, -2, 0), (1, 2, 0), (-2, 0, 1)]]


def cell_hash(cx, cy):
    """The two hash bytes for a cloud cell. Mirrors _cloud_at() in clouds.cc."""
    a = HASH_X[cx % CELLS_X] ^ HASH_Y[cy % CELLS_Y]
    return HASH_A[a & 31], HASH_B[a & 31]


def group_at(cx, cy):
    """The group in this cell as {pattern, x, y} in world units, or None.

    cx and cy are unmasked cell coordinates, so the position is absolute and
    the hash wraps - exactly how world.cc treats the map.
    """
    ha, hb = cell_hash(cx, cy)
    if (ha & GATE_MASK) != 0:
        return None
    return {
        "pattern": (ha >> 6) & (PATTERN_COUNT - 1),
        "x": cx * CELL_U + ((hb & 0x0F) << JITTER_SHIFT),
        "y": cy * CELL_U + ((hb >> 4) << JITTER_SHIFT),
    }


def rung_for_depth(depth):
    """Ladder rung for a camera-space depth, or None beyond the cull (§3.2)."""
    if depth > RUNG_DEPTH[0]:
        return None
    rung = 0
    while rung < RUNG_COUNT - 1 and depth <= RUNG_DEPTH[rung + 1]:
        rung += 1
    return rung
