#ifndef CLOUDDEF_H
#define CLOUDDEF_H

// Generated by tools/generate_clouds.py -- do not edit.
// Run `make clouds` after changing the constants at the top of that script.
//
// See docs/clouds.md: §2 for the placement, §3 for the size ladder.
// Hash tables from search seed 77.

#include <stdint.h>

// The cloud cell grid (§2.2). Cell index is the world position shifted down
// by kCloudCellShift and masked; the masks are the world's wrap.
static const uint16_t kCloudCellU = 2048;
static const uint8_t kCloudCellShift = 11;
static const uint8_t kCloudCellMaskX = 7;
static const uint8_t kCloudCellMaskY = 15;
static const uint8_t kCloudScanRadius = 2;

// A cell carries a group when (ha & kCloudGateMask) == 0 (§2.4).
static const uint8_t kCloudGateMask = 0x07;
static const uint8_t kCloudJitterShift = 7;

// Blob diameter (§3.1), deck altitude (§2.6) and the half-basis the group
// offsets are counted in (§2.5), all in 2 m units.
static const uint8_t kCloudBlobU = 96;
static const int16_t kCloudDeckU = 350;
static const uint8_t kCloudOffsetU = 48;

// The draw distance. Equal to the scan's guaranteed radius by construction -
// generate_clouds.py fails the build if they ever disagree (§2.2).
static const int16_t kCloudCullU = 4096;

// The size ladder (§3.2). Rungs 0..4 are one sprite and index
// kSpriteDefCloud1Sprite; 5..9 are a 1 x 2 stack and index
// kSpriteDefCloud2Sprite[rung - 5].
static const uint8_t kCloudRungCount = 10;
static const uint8_t kCloudRungStacked = 5;

static const uint8_t kCloudPatternCount = 4;
static const uint8_t kCloudBlobsPerGroup = 3;

extern const uint8_t kCloudHashX[8];
extern const uint8_t kCloudHashY[16];
extern const uint8_t kCloudHashA[32];
extern const uint8_t kCloudHashB[32];
extern const int16_t kCloudRungDepth[kCloudRungCount];
extern const int8_t kCloudGroupOffset[kCloudPatternCount][kCloudBlobsPerGroup][3];

#pragma compile("clouddef.cc")

#endif
