// Generated by tools/generate_clouds.py -- do not edit.
// Run `make clouds` after changing the constants at the top of that script.

#include "clouddef.h"

const uint8_t kCloudHashX[8] = {
    156, 56, 205, 150, 110, 26, 56, 180,
};

const uint8_t kCloudHashY[16] = {
    97, 240, 92, 212, 35, 135, 233, 175,
    14, 223, 24, 29, 17, 246, 232, 86,
};

// Presence in the low bits, pattern in the top two.
const uint8_t kCloudHashA[32] = {
    64, 209, 139, 157, 253, 217, 236, 49,
    247, 30, 199, 187, 46, 148, 154, 74,
    152, 150, 65, 48, 207, 62, 100, 86,
    239, 232, 74, 79, 47, 182, 38, 143,
};

// Jitter x in the low nibble, jitter y in the high one.
const uint8_t kCloudHashB[32] = {
    194, 154, 59, 249, 33, 170, 78, 109,
    228, 215, 0, 80, 105, 230, 208, 243,
    248, 219, 178, 89, 26, 72, 115, 136,
    250, 104, 90, 90, 88, 21, 198, 48,
};

// Largest depth at which each rung still applies, so rung
// selection is a compare chain and never a divide (§3.2):
//   rung 0:  3 x2 world px, out to  4096 units ( 8192 m)
//   rung 1:  5 x2 world px, out to  2458 units ( 4916 m)
//   rung 2:  7 x2 world px, out to  1755 units ( 3510 m)
//   rung 3:  9 x2 world px, out to  1365 units ( 2730 m)
//   rung 4: 11 x2 world px, out to  1117 units ( 2234 m)
//   rung 5: 13 x2 world px, out to   945 units ( 1890 m)
//   rung 6: 15 x2 world px, out to   819 units ( 1638 m)
//   rung 7: 17 x2 world px, out to   723 units ( 1446 m)
//   rung 8: 19 x2 world px, out to   647 units ( 1294 m)
//   rung 9: 21 x2 world px, out to   585 units ( 1170 m)
const int16_t kCloudRungDepth[kCloudRungCount] = {
    4096, 2458, 1755, 1365, 1117,
    945, 819, 723, 647, 585,
};

// Group layout (§2.5), in halves of kCloudOffsetU along the
// world x, y and z axes.
const int8_t kCloudGroupOffset[kCloudPatternCount][kCloudBlobsPerGroup][3] = {
    { { -2, -1,  0 }, {  2, -1,  0 }, {  0,  2,  1 } }, // pattern 0
    { { -1, -2,  0 }, { -1,  2,  0 }, {  2,  0,  1 } }, // pattern 1
    { { -2,  1,  0 }, {  2,  1,  0 }, {  0, -2,  1 } }, // pattern 2
    { {  1, -2,  0 }, {  1,  2,  0 }, { -2,  0,  1 } }, // pattern 3
};
