// Generated by tools/generate_clouds.py -- do not edit.
// Run `make clouds` after changing the constants at the top of that script.

#include "clouddef.h"

const uint8_t kCloudHashX[8] = {
    73, 214, 23, 77, 3, 15, 228, 67,
};

const uint8_t kCloudHashY[16] = {
    239, 82, 206, 191, 80, 194, 219, 150,
    220, 48, 148, 194, 197, 142, 53, 56,
};

// Presence in the low bits, pattern in the top two.
const uint8_t kCloudHashA[32] = {
    91, 116, 60, 79, 225, 145, 107, 223,
    254, 103, 248, 193, 211, 72, 27, 142,
    19, 158, 170, 200, 150, 138, 31, 167,
    201, 0, 198, 149, 151, 77, 2, 216,
};

// Jitter x in the low nibble, jitter y in the high one.
const uint8_t kCloudHashB[32] = {
    146, 162, 166, 127, 85, 130, 44, 210,
    35, 79, 107, 66, 170, 74, 147, 44,
    195, 197, 133, 161, 186, 173, 252, 199,
    135, 137, 186, 251, 90, 254, 28, 202,
};

// Largest depth at which each rung still applies, so rung
// selection is a compare chain and never a divide (§3.2):
//   rung 0:  3 x2 world px, out to  4096 units ( 8192 m)
//   rung 1:  5 x2 world px, out to  2458 units ( 4916 m)
//   rung 2:  7 x2 world px, out to  1755 units ( 3510 m)
//   rung 3:  9 x2 world px, out to  1365 units ( 2730 m)
//   rung 4: 11 x2 world px, out to  1117 units ( 2234 m)
//   rung 5: 13 x2 world px, out to   945 units ( 1890 m)
//   rung 6: 15 x2 world px, out to   819 units ( 1638 m)
//   rung 7: 17 x2 world px, out to   723 units ( 1446 m)
//   rung 8: 19 x2 world px, out to   647 units ( 1294 m)
//   rung 9: 21 x2 world px, out to   585 units ( 1170 m)
const int16_t kCloudRungDepth[kCloudRungCount] = {
    4096, 2458, 1755, 1365, 1117,
    945, 819, 723, 647, 585,
};

// Group layout (§2.5), in halves of kCloudOffsetU along the
// world x, y and z axes.
const int8_t kCloudGroupOffset[kCloudPatternCount][kCloudBlobsPerGroup][3] = {
    { { -2, -1,  0 }, {  2, -1,  0 }, {  0,  2,  1 } }, // pattern 0
    { { -1, -2,  0 }, { -1,  2,  0 }, {  2,  0,  1 } }, // pattern 1
    { { -2,  1,  0 }, {  2,  1,  0 }, {  0, -2,  1 } }, // pattern 2
    { {  1, -2,  0 }, {  1,  2,  0 }, { -2,  0,  1 } }, // pattern 3
};
