// Generated by tools/generate_clouds.py -- do not edit.
// Run `make clouds` after changing the constants at the top of that script.

#include "clouddef.h"

const uint8_t kCloudHashX[8] = {
    129, 166, 101, 123, 98, 58, 149, 243,
};

const uint8_t kCloudHashY[16] = {
    121, 74, 1, 143, 14, 254, 88, 97,
    198, 93, 169, 164, 60, 44, 133, 240,
};

// Presence in the low bits, pattern in the top two.
const uint8_t kCloudHashA[32] = {
    104, 115, 98, 36, 41, 102, 224, 39,
    51, 108, 168, 44, 48, 236, 40, 54,
    139, 227, 62, 179, 28, 206, 126, 112,
    241, 206, 70, 196, 6, 17, 26, 253,
};

// Jitter x in the low nibble, jitter y in the high one.
const uint8_t kCloudHashB[32] = {
    20, 183, 221, 60, 131, 250, 28, 241,
    48, 75, 152, 47, 8, 248, 180, 212,
    0, 31, 246, 74, 13, 4, 122, 45,
    238, 58, 199, 243, 52, 69, 122, 133,
};

// Largest depth at which each rung still applies, so rung
// selection is a compare chain and never a divide (§3.2):
//   rung 0:  3 x2 world px, out to  4096 units ( 8192 m)
//   rung 1:  5 x2 world px, out to  2458 units ( 4916 m)
//   rung 2:  7 x2 world px, out to  1755 units ( 3510 m)
//   rung 3:  9 x2 world px, out to  1365 units ( 2730 m)
//   rung 4: 11 x2 world px, out to  1117 units ( 2234 m)
//   rung 5: 13 x2 world px, out to   945 units ( 1890 m)
//   rung 6: 15 x2 world px, out to   819 units ( 1638 m)
//   rung 7: 17 x2 world px, out to   723 units ( 1446 m)
//   rung 8: 19 x2 world px, out to   647 units ( 1294 m)
//   rung 9: 21 x2 world px, out to   585 units ( 1170 m)
const int16_t kCloudRungDepth[kCloudRungCount] = {
    4096, 2458, 1755, 1365, 1117,
    945, 819, 723, 647, 585,
};

// Group layout (§2.5), in halves of kCloudOffsetU along the
// world x, y and z axes.
const int8_t kCloudGroupOffset[kCloudPatternCount][kCloudBlobsPerGroup][3] = {
    { { -2, -1,  0 }, {  2, -1,  0 }, {  0,  2,  1 } }, // pattern 0
    { { -1, -2,  0 }, { -1,  2,  0 }, {  2,  0,  1 } }, // pattern 1
    { { -2,  1,  0 }, {  2,  1,  0 }, {  0, -2,  1 } }, // pattern 2
    { {  1, -2,  0 }, {  1,  2,  0 }, { -2,  0,  1 } }, // pattern 3
};
