// Generated by tools/generate_map_tiles.py -- do not edit.
// Source art: gfx/ppilot_map_tiles.png

#ifndef MAPDEFS_H
#define MAPDEFS_H

#include <stdint.h>

static const uint8_t kMapTileCount = 18;
static const uint8_t kMapDigitCount = 4;

// Group bases, so a WorldMapType becomes a tile index with
// shifts and adds only. Empty ground (MAP_DOT_GROUND) selects a
// grid variant by ((row & 1) << 1) | (col & 1).
static const uint8_t kMapTileGrid = 0;
static const uint8_t kMapTileDot = 4;
static const uint8_t kMapTileObj = 9;

static const uint8_t kMapTileGridEvenEven = 0;
static const uint8_t kMapTileGridEvenOdd = 1;
static const uint8_t kMapTileGridOddEven = 2;
static const uint8_t kMapTileGridOddOdd = 3;
static const uint8_t kMapTileDotBlack = 4;
static const uint8_t kMapTileDotWhite = 5;
static const uint8_t kMapTileDotCyan = 6;
static const uint8_t kMapTileDotBlue = 7;
static const uint8_t kMapTileDotYellow = 8;
static const uint8_t kMapTileRunway = 9;
static const uint8_t kMapTileField = 10;
static const uint8_t kMapTileFieldSparse = 11;
static const uint8_t kMapTileFieldYellow = 12;
static const uint8_t kMapTileFieldYellowSparse = 13;
static const uint8_t kMapTilePond = 14;
static const uint8_t kMapTileLake = 15;
static const uint8_t kMapTileTown = 16;
static const uint8_t kMapTileCity = 17;

// Transposed: row index outer, tile index inner, so the
// compositor does eight indexed loads off one index register.
extern const uint8_t kMapTileRows[8][kMapTileCount];
// Bit pair 10, written to the screen RAM low nibble.
extern const uint8_t kMapTileLo[kMapTileCount];
// Bit pair 11, written to color RAM.
extern const uint8_t kMapTileCol[kMapTileCount];

// Overlay stencils for navpoints 1..4. Each byte holds 11 in
// every ink pair; the draw is
//   dst[r] = (dst[r] & ~mask[r]) | (mask[r] & 0x55)
// which deposits 01 into the ink pairs and leaves the object
// art in every other pair untouched.
extern const uint8_t kMapDigitMask[kMapDigitCount][8];

#pragma compile("mapdefs.cc")

#endif // MAPDEFS_H
