#include "musicdef.h"

// Generated by tools/generate_music.py from lib/music.py.
// Do not edit; run `make music`.

#ifdef __ENABLE_SOUND__

// Octave-6 note table (12 entries)
const uint16_t kMusicNoteTable[12] = {
    17820, 18880, 20003, 21192, 22452, 23787, 25202, 26700, 28288, 29970, 31752, 33640
};

// Chord table: 7 distinct of 24 bars, 52 bytes instead of 96.
const music_chord_t kMusicChordPat[7] = {
    { 38, { 62, 65, 69 } }, // Dm
    { 34, { 58, 62, 65 } }, // A#
    { 36, { 60, 64, 67 } }, // C
    { 33, { 57, 60, 64 } }, // Am
    { 33, { 57, 61, 64 } }, // A7
    { 29, { 65, 69, 72 } }, // F
    { 31, { 62, 67, 70 } }, // Gm
};

const uint8_t kMusicChordBar[24] = {
      0,   1,   2,   3,   0,   1,   2,   4,   0,   5,   2,   6,
      0,   1,   2,   4,   0,   1,   2,   3,   0,   5,   6,   4,
};

// Master volume per bar (24 entries, 0..15)
const uint8_t kMusicVolMap[24] = {
     11,  12,  13,  14,  15,  15,  15,  15,
     15,  15,  15,  15,  15,  15,  15,  15,
     15,  15,  15,  15,  15,  15,  13,  11,
};

// Lead start midi notes, 0 = rest: 20 distinct bars of 24, 344 bytes instead of 384.
const uint8_t kMusicLeadStartPat[20][16] = {
    {   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 }, // pattern 0
    {  62,   0,   0,   0,   0,   0,   0,   0,  65,   0,   0,   0,  69,   0,   0,   0 }, // pattern 1
    {  67,   0,   0,   0,   0,   0,   0,   0,  65,   0,   0,   0,  64,   0,   0,   0 }, // pattern 2
    {  65,   0,   0,   0,   0,   0,   0,   0,  64,   0,   0,   0,  62,   0,   0,   0 }, // pattern 3
    {  64,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 }, // pattern 4
    {  62,   0,   0,   0,  65,   0,   0,   0,  69,   0,   0,   0,  74,   0,   0,   0 }, // pattern 5
    {  72,   0,   0,   0,  69,   0,   0,   0,  65,   0,   0,   0,  69,   0,   0,   0 }, // pattern 6
    {  67,   0,   0,   0,  64,   0,   0,   0,  60,   0,   0,   0,  64,   0,   0,   0 }, // pattern 7
    {  65,   0,   0,   0,  62,   0,   0,   0,  58,   0,   0,   0,  62,   0,   0,   0 }, // pattern 8
    {  77,   0,   0,   0,  74,   0,   0,   0,  69,   0,   0,   0,  74,   0,   0,   0 }, // pattern 9
    {  76,   0,   0,   0,  72,   0,   0,   0,  67,   0,   0,   0,  72,   0,   0,   0 }, // pattern 10
    {  73,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 }, // pattern 11
    {  77,   0,  76,   0,  74,   0,  72,   0,  74,   0,   0,   0,  69,   0,   0,   0 }, // pattern 12
    {  74,   0,  72,   0,  70,   0,  69,   0,  70,   0,   0,   0,  65,   0,   0,   0 }, // pattern 13
    {  72,   0,  70,   0,  69,   0,  67,   0,  69,   0,   0,   0,  64,   0,   0,   0 }, // pattern 14
    {  64,   0,  65,   0,  67,   0,  69,   0,  70,   0,  72,   0,  73,   0,   0,   0 }, // pattern 15
    {  74,   0,   0,   0,  77,   0,   0,   0,  81,   0,   0,   0,  77,   0,   0,   0 }, // pattern 16
    {  72,   0,   0,   0,  76,   0,   0,   0,  79,   0,   0,   0,  76,   0,   0,   0 }, // pattern 17
    {  74,   0,   0,   0,  77,   0,   0,   0,  79,   0,   0,   0,  82,   0,   0,   0 }, // pattern 18
    {  81,   0,   0,   0,  79,   0,   0,   0,  77,   0,   0,   0,  76,   0,   0,   0 }, // pattern 19
};

const uint8_t kMusicLeadStartBar[24] = {
      0,   0,   0,   0,   1,   2,   3,   4,   5,   6,   7,   8,
      5,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,
};

// Bass start midi notes, 0 = rest: 11 distinct bars of 24, 200 bytes instead of 384.
const uint8_t kMusicBassStartPat[11][16] = {
    {  38,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 }, // pattern 0
    {  34,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 }, // pattern 1
    {  36,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 }, // pattern 2
    {  33,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 }, // pattern 3
    {  38,   0,  38,   0,  38,   0,  50,   0,  38,   0,  38,   0,  45,   0,  50,   0 }, // pattern 4
    {  34,   0,  34,   0,  34,   0,  46,   0,  34,   0,  34,   0,  41,   0,  46,   0 }, // pattern 5
    {  36,   0,  36,   0,  36,   0,  48,   0,  36,   0,  36,   0,  43,   0,  48,   0 }, // pattern 6
    {  33,   0,  33,   0,  33,  33,  45,   0,  33,   0,  40,   0,  45,   0,  43,  45 }, // pattern 7
    {  29,   0,  29,   0,  29,   0,  41,   0,  29,   0,  29,   0,  36,   0,  41,   0 }, // pattern 8
    {  31,   0,  31,   0,  31,  31,  43,   0,  31,   0,  38,   0,  43,   0,  41,  43 }, // pattern 9
    {  31,   0,  31,   0,  31,   0,  43,   0,  31,   0,  31,   0,  38,   0,  43,   0 }, // pattern 10
};

const uint8_t kMusicBassStartBar[24] = {
      0,   1,   2,   3,   4,   5,   6,   7,   4,   8,   6,   9,
      4,   5,   6,   7,   4,   5,   6,   7,   4,   8,  10,   7,
};

// Lead gate, 1 bit per row LSB first. MUSIC_LEAD_ON(row): 3 distinct bars of 24, 30 bytes instead of 48.
const uint8_t kMusicLeadOnBitsPat[3][2] = {
    {   0,   0 }, // pattern 0
    { 255, 255 }, // pattern 1
    { 255,   0 }, // pattern 2
};

const uint8_t kMusicLeadOnBitsBar[24] = {
      0,   0,   0,   0,   1,   1,   1,   2,   1,   1,   1,   1,
      1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,
};

// Drum hits, 2 bits per row. MUSIC_DRUM_AT(row): 5 distinct bars of 24, 44 bytes instead of 96.
const uint8_t kMusicDrumBitsPat[5][4] = {
    {   0,   0,   0,   0 }, // pattern 0
    {  51,  51,  51,  51 }, // pattern 1
    {  49,  18,  49,  50 }, // pattern 2
    {  49,  18,  17,  18 }, // pattern 3
    {  49,  18,  17, 154 }, // pattern 4
};

const uint8_t kMusicDrumBitsBar[24] = {
      0,   0,   0,   0,   1,   1,   1,   1,   2,   2,   2,   3,
      2,   2,   2,   4,   2,   2,   2,   3,   2,   2,   2,   4,
};

const music_instrument_t kMusicInsLead = { 5, 197, 64, 0, 0, 0 };
const music_instrument_t kMusicInsBass = { 6, 132, 64, 0, 0, 0 };
const music_instrument_t kMusicInsArp  = { 0, 243, 32, 0, 0, 0 };

// Indexed by MUSIC_DRUM_AT(row) - 1.
const music_instrument_t kMusicDrumIns[3] = {
    { 0, 240, 128, 5, 4096, 665 }, // kick: 4096 -> 768 over 5 frames
    { 0, 240, 128, 4, 14336, 0 }, // snare: 14336 -> 14336 over 4 frames
    { 0, 240, 128, 2, 20480, 0 }, // hat: 20480 -> 20480 over 2 frames
};

#endif // __ENABLE_SOUND__
