// Generated by tools/generate_planes.py from lib/planes.py -- do not edit.
// Regenerate with `make planes` after changing the reference.
#ifndef PLANEDEF_H
#define PLANEDEF_H

#include <stdint.h>

// The model, in eighths of a metre at the exaggeration, as shared products:
// every distinct magnitude is multiplied by k once, and every (axis,
// magnitude) pair by the two screen components of its axis once
// (planeproj.h).
static const uint8_t kPlaneMagCount = 16;
static const uint8_t kPlaneMags[16] = {27, 66, 5, 30, 13, 9, 32, 20, 43, 45, 25, 40, 18, 55, 6, 1};
static const uint8_t kPlanePairCount = 15;

// Fuselage stations, nose to tail: fore reference and radius magnitude. A
// reference is a pair index + 1, negated for a negative coordinate.
static const uint8_t kPlaneBodyCount = 3;
static const int8_t kPlaneBodyFore[3] = {14, 15, -10};
static const uint8_t kPlaneBodyRadius[3] = {14, 14, 15};
// The wing hub, on the fore axis: magnitude index and sign.
static const uint8_t kPlaneHubMag = 7;
static const int8_t kPlaneHubSign = 1;

// The size cap and the pixel-size ladder (docs/planes.md section 4).
static const uint8_t kPlaneMaxRadius = 68;
static const uint16_t kPlaneKMax = 150;
static const uint8_t kPlaneDDot = 3;
static const uint8_t kPlaneD1x = 21;
static const uint8_t kPlaneYLimit = 41;
// Hysteresis, as the integer forms of lib/planes.py's comparisons against
// 0.87 of each limit: demote at or below, hold while above.
static const uint8_t kPlaneDDotDown = 2;
static const uint8_t kPlaneD1xDown = 18;
static const uint8_t kPlaneYHold = 35;
static const uint8_t kPlaneColsHold[3] = {0, 20, 40};  // by xs
static const uint8_t kPlaneRowsHold[3] = {0, 17, 34};  // by ys

// 65536 / dy for every edge height; entries 0 to 2 are never read (dy 1
// and 2 are shifts, and 32768 would not fit a signed multiplier).
static const uint16_t kPlaneRecip[42] = {0, 0, 0, 21845, 16384, 13107, 10922, 9362, 8192, 7281, 6553, 5957, 5461, 5041, 4681, 4369, 4096, 3855, 3640, 3449, 3276, 3120, 2978, 2849, 2730, 2621, 2520, 2427, 2340, 2259, 2184, 2114, 2048, 1985, 1927, 1872, 1820, 1771, 1724, 1680, 1638, 1598};

#endif
