// Generated by tools/generate_planes.py from lib/planes.py -- do not edit.
// Regenerate with `make planes` after changing the reference.
//
// The projection of the model's fixed part, as straight-line code: every
// (axis, magnitude) product, and the wing, tailplane and fin vertices as sums
// of those. c64o/planes.cc includes it after the arrays it reads and writes.
#ifndef PLANEPROJ_H
#define PLANEPROJ_H

// _ox[p], _oy[p]: pair p - 1's screen offset, its axis's screen components
// times its magnitude. Index 0 is the zero product.
static void _project_pairs(const mat3_t *axes) {
  int16_t fy = axes->front.y, fz = axes->front.z;
  int16_t ly = axes->left.y, lz = axes->left.z;
  int16_t uy = axes->up.y, uz = axes->up.z;
  _ox[1] = vec_fastmul8p8(fy, _px[0]);
  _oy[1] = vec_fastmul8p8(fz, _px[0]);
  _ox[2] = vec_fastmul8p8(ly, _px[1]);
  _oy[2] = vec_fastmul8p8(lz, _px[1]);
  _ox[3] = vec_fastmul8p8(uy, _px[2]);
  _oy[3] = vec_fastmul8p8(uz, _px[2]);
  _ox[4] = vec_fastmul8p8(fy, _px[3]);
  _oy[4] = vec_fastmul8p8(fz, _px[3]);
  _ox[5] = vec_fastmul8p8(fy, _px[4]);
  _oy[5] = vec_fastmul8p8(fz, _px[4]);
  _ox[6] = vec_fastmul8p8(fy, _px[5]);
  _oy[6] = vec_fastmul8p8(fz, _px[5]);
  _ox[7] = vec_fastmul8p8(fy, _px[6]);
  _oy[7] = vec_fastmul8p8(fz, _px[6]);
  _ox[8] = vec_fastmul8p8(ly, _px[7]);
  _oy[8] = vec_fastmul8p8(lz, _px[7]);
  _ox[9] = vec_fastmul8p8(fy, _px[8]);
  _oy[9] = vec_fastmul8p8(fz, _px[8]);
  _ox[10] = vec_fastmul8p8(fy, _px[9]);
  _oy[10] = vec_fastmul8p8(fz, _px[9]);
  _ox[11] = vec_fastmul8p8(fy, _px[10]);
  _oy[11] = vec_fastmul8p8(fz, _px[10]);
  _ox[12] = vec_fastmul8p8(fy, _px[11]);
  _oy[12] = vec_fastmul8p8(fz, _px[11]);
  _ox[13] = vec_fastmul8p8(uy, _px[12]);
  _oy[13] = vec_fastmul8p8(uz, _px[12]);
  _ox[14] = vec_fastmul8p8(fy, _px[13]);
  _oy[14] = vec_fastmul8p8(fz, _px[13]);
  _ox[15] = vec_fastmul8p8(fy, _px[2]);
  _oy[15] = vec_fastmul8p8(fz, _px[2]);
}

// The flat surfaces: the centre less each coordinate's product.
static void _project_flat(void) {
  // wing
  _vx[0] = (int16_t)(_cx - _ox[1] - _ox[2] + _ox[3]);
  _vy[0] = (int16_t)(_cy - _oy[1] - _oy[2] + _oy[3]);
  _vx[1] = (int16_t)(_cx - _ox[4] + _ox[3]);
  _vy[1] = (int16_t)(_cy - _oy[4] + _oy[3]);
  _vx[2] = (int16_t)(_cx - _ox[1] + _ox[2] + _ox[3]);
  _vy[2] = (int16_t)(_cy - _oy[1] + _oy[2] + _oy[3]);
  _vx[3] = (int16_t)(_cx - _ox[5] + _ox[2] + _ox[3]);
  _vy[3] = (int16_t)(_cy - _oy[5] + _oy[2] + _oy[3]);
  _vx[4] = (int16_t)(_cx - _ox[6] + _ox[3]);
  _vy[4] = (int16_t)(_cy - _oy[6] + _oy[3]);
  _vx[5] = (int16_t)(_cx - _ox[5] - _ox[2] + _ox[3]);
  _vy[5] = (int16_t)(_cy - _oy[5] - _oy[2] + _oy[3]);
  // tailplane
  _vx[6] = (int16_t)(_cx + _ox[7] - _ox[8]);
  _vy[6] = (int16_t)(_cy + _oy[7] - _oy[8]);
  _vx[7] = (int16_t)(_cx + _ox[4]);
  _vy[7] = (int16_t)(_cy + _oy[4]);
  _vx[8] = (int16_t)(_cx + _ox[7] + _ox[8]);
  _vy[8] = (int16_t)(_cy + _oy[7] + _oy[8]);
  _vx[9] = (int16_t)(_cx + _ox[9] + _ox[8]);
  _vy[9] = (int16_t)(_cy + _oy[9] + _oy[8]);
  _vx[10] = (int16_t)(_cx + _ox[10]);
  _vy[10] = (int16_t)(_cy + _oy[10]);
  _vx[11] = (int16_t)(_cx + _ox[9] - _ox[8]);
  _vy[11] = (int16_t)(_cy + _oy[9] - _oy[8]);
  // fin
  _vx[12] = _vx[10];
  _vy[12] = _vy[10];
  _vx[13] = (int16_t)(_cx + _ox[11]);
  _vy[13] = (int16_t)(_cy + _oy[11]);
  _vx[14] = (int16_t)(_cx + _ox[12] - _ox[13]);
  _vy[14] = (int16_t)(_cy + _oy[12] - _oy[13]);
  _vx[15] = (int16_t)(_cx + _ox[10] - _ox[13]);
  _vy[15] = (int16_t)(_cy + _oy[10] - _oy[13]);
  _poly_start[0] = 0;
  _poly_start[1] = 6;
  _poly_start[2] = 12;
  _poly_start[3] = 16;
  _poly_count = 3;
  _vert_count = 16;
}

#endif
