// Generated by tools/generate_planes.py from lib/planes.py -- do not edit.
// Regenerate with `make planes` after changing the reference.
#ifndef PLANEDEF_H
#define PLANEDEF_H

#include <stdint.h>

#ifndef __OSCAR64__
#define __striped
#endif

// The model, in eighths of a metre at the exaggeration, as shared products:
// every distinct magnitude is multiplied by k once, and every (axis,
// magnitude) pair by the two screen components of its axis once.
static const uint8_t kPlaneMagCount = 16;
static const uint8_t kPlaneMags[16] = {27, 66, 5, 30, 13, 9, 32, 20, 43, 45, 25, 40, 18, 55, 6, 1};
// Pair p's magnitude, for p = 1 .. 15; the pairs of axis a (front, left, up)
// are kPlaneAxisPairs[a] .. kPlaneAxisPairs[a + 1] - 1.
static const uint8_t kPlanePairMag[16] = {0, 0, 3, 4, 5, 6, 8, 9, 10, 11, 13, 2, 1, 7, 2, 12};
static const uint8_t kPlaneAxisPairs[4] = {1, 12, 14, 16};

// The wing, tailplane and fin: each vertex's fore, left and up terms. A term
// indexes the product tables -- pair p's product negated at p, as is at
// 16 + p, zero at 0 -- so a vertex relative to the centre is their sum.
static const uint8_t kPlaneVertCount = 16;
static const uint8_t kPlaneVertFore[16] = {1, 2, 1, 3, 4, 3, 21, 18, 21, 22, 23, 22, 23, 24, 25, 23};
static const uint8_t kPlaneVertLeft[16] = {12, 0, 28, 28, 0, 12, 13, 0, 29, 29, 0, 13, 0, 0, 0, 0};
static const uint8_t kPlaneVertUp[16] = {30, 30, 30, 30, 30, 30, 0, 0, 0, 0, 0, 0, 0, 0, 15, 15};
static const uint8_t kPlanePolyStart[4] = {0, 6, 12, 16};

// Fuselage stations, nose to tail: fore term and radius magnitude.
static const uint8_t kPlaneBodyCount = 3;
static const uint8_t kPlaneBodyFore[3] = {10, 11, 23};
static const uint8_t kPlaneBodyRadius[3] = {14, 14, 15};

// The size cap and the pixel-size ladder (docs/planes.md section 4).
static const uint8_t kPlaneMaxRadius = 68;
static const uint16_t kPlaneKMax = 150;
static const uint8_t kPlaneDDot = 3;
static const uint8_t kPlaneD1x = 21;
static const uint8_t kPlaneYLimit = 41;
// Hysteresis, as the integer forms of lib/planes.py's comparisons against
// 0.87 of each limit: demote at or below, hold while above.
static const uint8_t kPlaneDDotDown = 2;
static const uint8_t kPlaneD1xDown = 18;
static const uint8_t kPlaneYHold = 35;
static const uint8_t kPlaneColsHold[3] = {0, 20, 40};  // by xs
static const uint8_t kPlaneRowsHold[3] = {0, 17, 34};  // by ys

// 65536 / dy for every edge height; entries 0 to 2 are never read (dy 1
// and 2 are shifts, and 32768 would not fit a signed multiplier). Striped:
// all the low bytes, then all the high ones, so planes_asm.cc indexes both
// halves with dy itself.
static const uint8_t kPlaneRecipCount = 42;
__striped static const uint16_t kPlaneRecip[kPlaneRecipCount] = {0, 0, 0, 21845, 16384, 13107, 10922, 9362, 8192, 7281, 6553, 5957, 5461, 5041, 4681, 4369, 4096, 3855, 3640, 3449, 3276, 3120, 2978, 2849, 2730, 2621, 2520, 2427, 2340, 2259, 2184, 2114, 2048, 1985, 1927, 1872, 1820, 1771, 1724, 1680, 1638, 1598};

#endif
