// Generated by tools/generate_sprites.py from
// gfx/ppilot_sprites_concept.png. Do not edit; run `make sprites`.

#ifndef TITLEDEF_H
#define TITLEDEF_H

#include <stdint.h>

// The title screen aircraft: one drawing across a 2 x 2 block of
// multicolour sprites, in reading order - top left, top right, bottom
// left, bottom right. 48 x 42 screen pixels.
static const uint8_t kTitleDefCols = 2;
static const uint8_t kTitleDefRows = 2;
static const uint8_t kTitleDefBitmapCount = 4;
// First VIC sprite block; the four are consecutive. c64o/mem.h places
// the bitmaps and asserts that its address agrees with this.
static const uint8_t kTitleDefBitmapBase = 60;

// Bit pair 01 and 11 are the two screen-wide sprite multicolour
// registers; bit pair 10 is each sprite's own colour, and all four
// blocks are given the same one.
static const uint8_t kTitleDefColorMc0 = 2;
static const uint8_t kTitleDefColorMain = 10;
static const uint8_t kTitleDefColorMc1 = 15;

#endif
