#!/usr/bin/env python3
"""Ratchet on implicit 16-bit narrowings in the host test build.

oscar64's ``int`` is 16 bits and the host's is 32, and C promotes every operand
narrower than ``int`` before it does any arithmetic. So an intermediate that
wraps on the 6510 does not wrap under g++, and a host test can pass against
arithmetic the target never performed. ``c64o/test/int16.h`` has the measured
examples; ``c64o/test/target_test.cc`` is the only exact check.

Every place the host build implicitly narrows an ``int`` back down is a place
where that divergence *could* live. Most are harmless. This does not decide
which - it counts them per file and fails when the count moves, so a new one has
to be looked at and written into the baseline deliberately.

**Counts, not line numbers.** A line-anchored baseline would churn on every edit
above a site. The cost is that a removed narrowing and an added one in the same
file cancel; the benefit is a file nobody has to touch to edit code.

Reads compiler stderr on stdin, compares to the baseline, prints what moved.

    ... 2>&1 | python3 tools/check_narrowing.py c64o/test/narrowing.baseline
    ... 2>&1 | python3 tools/check_narrowing.py --update <baseline>
"""

import collections
import os
import re
import sys

# clang: "path/x.cc:12:34: warning: implicit conversion loses integer precision"
_WARN = re.compile(r"^(.*?):(\d+):(\d+): warning: (.*)$")


def _normalise(path):
    """A repo-relative path, so the counts do not depend on the build's cwd."""
    path = os.path.normpath(path)
    for marker in ("/c64o/", "/tools/", "/lib/"):
        idx = path.find(marker)
        if idx != -1:
            return path[idx + 1 :]
    return os.path.basename(path)


def collect(lines):
    counts = collections.Counter()
    sites = collections.defaultdict(list)
    seen = set()
    for line in lines:
        m = _WARN.match(line.rstrip("\n"))
        if not m:
            continue
        path, row, col, text = m.groups()
        key = (_normalise(path), row, col)
        if key in seen:  # the same header pulled into several suites
            continue
        seen.add(key)
        counts[key[0]] += 1
        sites[key[0]].append(f"  {key[0]}:{row}:{col}  {text}")
    return counts, sites


def read_baseline(path):
    counts = collections.Counter()
    if not os.path.exists(path):
        return None
    with open(path) as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            name, _, n = line.rpartition(" ")
            counts[name.strip()] = int(n)
    return counts


HEADER = """\
# Implicit 16-bit narrowings in the host test build, per file.
#
# Generated by tools/check_narrowing.py; regenerate with
#   make -C c64o/test narrowing-update
#
# This is a prompt, not a verdict, and it is worth being clear about both
# halves of that.
#
# It over-reports. Most narrowings here are deliberate and safe - a value that
# provably fits being put back in the byte or word it came from. Silencing them
# with an explicit cast would be worse than leaving them: the cast does not make
# the host agree with the 6510, it only stops the compiler mentioning the
# difference. i16((sx + 2) >> 2) is still 8192 on the host and -8192 on a C64.
#
# It under-reports, and badly. The check is a compiler heuristic and it is blind
# to the case that matters most: it fires on the *result* being too wide for the
# destination, and the bugs here are ones where the result fits and only the
# intermediate overflowed. `(sx + 2) >> 2` with sx an int16_t - the expression
# that shipped broken in poly.cc - produces no warning at all, as a parameter, a
# volatile global or a static, at -O0 or -O2, because its result is inside
# [-8191, 8192] either way. It is only *different*: 8192 here, -8192 on a 6510.
#
# What it does catch is the other shape: `(int16_t)(-cy) << 8 >> 8`, where the
# narrowing is visible in the type. That was a real bug too (mul_test.cc), so
# this is worth running - it is just not a safety net.
#
# So: when a count moves, read the site and decide. If the intermediate can
# leave 16 bits and the test compares against it, the reference value needs
# int16.h's i16() at each step the target truncates at. And because of the hole
# above, a clean run here says nothing - the case belongs in target_test.cc,
# which runs the arithmetic on a real 6510 and is the only exact answer.
"""


def main():
    args = sys.argv[1:]
    update = "--update" in args
    args = [a for a in args if a != "--update"]
    if len(args) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    baseline_path = args[0]

    counts, sites = collect(sys.stdin)

    if update:
        with open(baseline_path, "w") as f:
            f.write(HEADER)
            for name in sorted(counts):
                f.write(f"{name} {counts[name]}\n")
        total = sum(counts.values())
        print(f"check_narrowing: wrote {baseline_path} ({total} in {len(counts)} files)")
        return 0

    baseline = read_baseline(baseline_path)
    if baseline is None:
        print(f"check_narrowing: no baseline at {baseline_path}", file=sys.stderr)
        print("  create one with: make -C c64o/test narrowing-update", file=sys.stderr)
        return 1

    added = {k: counts[k] - baseline.get(k, 0) for k in counts if counts[k] > baseline.get(k, 0)}
    removed = {k: baseline[k] - counts.get(k, 0) for k in baseline if baseline[k] > counts.get(k, 0)}

    if not added and not removed:
        total = sum(counts.values())
        print(f"check_narrowing: {total} narrowings, all in the baseline")
        return 0

    for name, n in sorted(added.items()):
        print(f"check_narrowing: {name} has {n} new narrowing(s):", file=sys.stderr)
        for s in sites[name]:
            print(s, file=sys.stderr)
    for name, n in sorted(removed.items()):
        print(f"check_narrowing: {name} has {n} fewer than the baseline.", file=sys.stderr)

    print("", file=sys.stderr)
    print("Read each new site and decide whether the intermediate can leave 16", file=sys.stderr)
    print("bits (c64o/test/int16.h). Then: make -C c64o/test narrowing-update", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
