#!/usr/bin/env python3
"""Generate the C64 traffic-sprite tables from the reference in lib/planes.py.

  tools/generate_planes.py                  writes c64o/planedef.h and planeproj.h
  tools/generate_planes.py --cases <path>   writes the host test's cases
  tools/generate_planes.py --target <path>  writes the on-target test's cases

The model reaches c64o/planes.cc as shared products: every distinct model
magnitude is multiplied by k once, every (axis, magnitude) pair by its axis
once, and each vertex is a sum of those -- the sharing docs/planes.md section
3 costs the projection by. c64o/planeproj.h writes the products and the
flat-surface vertices out as straight-line code; c64o/planedef.h is the
renderer's constants and the tables the rest reads. Both are checked in;
change lib/planes.py and run `make planes`.

The cases are camera-space inputs and the hash of what lib/planes.py renders
from them, for c64o/test/planes_test.cc to hold c64o/planes.cc to the
reference. They are 4,000 cases and a third of a megabyte, so they are not
checked in: c64o/test/Makefile regenerates them for every build of the test.
"""

import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from lib import planes  # noqa: E402
from lib.planes import (Model, State, orient, place, q88, to_cam, jround,  # noqa: E402
                        render, fnv1a)

DEF_PATH = os.path.join(ROOT, "c64o", "planedef.h")
PROJ_PATH = os.path.join(ROOT, "c64o", "planeproj.h")


def model_tables(model):
    g = model.geometry
    pairs, mags = [], []

    def mag(m):
        if m not in mags:
            mags.append(m)
        return mags.index(m)

    def ref(axis, v):
        """A coordinate as a signed reference: pair index + 1, negated for a
        negative value, 0 for zero."""
        if v == 0:
            return 0
        key = (axis, mag(abs(v)))
        if key not in pairs:
            pairs.append(key)
        i = pairs.index(key) + 1
        return -i if v < 0 else i

    verts, starts = [], []
    for part in ("wing", "stab", "fin"):
        starts.append(len(verts))
        for p in g[part]:
            verts.append(tuple(ref(axis, v) for axis, v in enumerate(p)))
    starts.append(len(verts))
    body_fore = [ref(0, f) for f, _ in g["body"]]
    body_radius = [mag(r) for _, r in g["body"]]
    # The hub is only projected when the silhouette overruns -- a guard -- so
    # it is a magnitude and a sign, not one of the per-frame products.
    hf = g["hub"][0]
    hub = (mag(abs(hf)), -1 if hf < 0 else 1)
    return mags, pairs, verts, starts, body_fore, body_radius, hub


def floor_of(x):
    return int(math.floor(x))


def write_def(model):
    mags, pairs, verts, starts, body_fore, body_radius, hub = model_tables(model)
    assert len(mags) < 256 and len(pairs) < 128
    h = planes.HYSTERESIS
    out = []
    w = out.append
    w("// Generated by tools/generate_planes.py from lib/planes.py -- do not edit.")
    w("// Regenerate with `make planes` after changing the reference.")
    w("#ifndef PLANEDEF_H")
    w("#define PLANEDEF_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w("// The model, in eighths of a metre at the exaggeration, as shared products:")
    w("// every distinct magnitude is multiplied by k once, and every (axis,")
    w("// magnitude) pair by the two screen components of its axis once")
    w("// (planeproj.h).")
    w("static const uint8_t kPlaneMagCount = %d;" % len(mags))
    w("static const uint8_t kPlaneMags[%d] = {%s};" % (len(mags), ", ".join(map(str, mags))))
    w("static const uint8_t kPlanePairCount = %d;" % len(pairs))
    w("")
    w("// Fuselage stations, nose to tail: fore reference and radius magnitude. A")
    w("// reference is a pair index + 1, negated for a negative coordinate.")
    w("static const uint8_t kPlaneBodyCount = %d;" % len(body_fore))
    w("static const int8_t kPlaneBodyFore[%d] = {%s};" % (len(body_fore), ", ".join(map(str, body_fore))))
    w("static const uint8_t kPlaneBodyRadius[%d] = {%s};" % (len(body_radius), ", ".join(map(str, body_radius))))
    w("// The wing hub, on the fore axis: magnitude index and sign.")
    w("static const uint8_t kPlaneHubMag = %d;" % hub[0])
    w("static const int8_t kPlaneHubSign = %d;" % hub[1])
    w("")
    w("// The size cap and the pixel-size ladder (docs/planes.md section 4).")
    w("static const uint8_t kPlaneMaxRadius = %d;" % model.max_radius)
    w("static const uint16_t kPlaneKMax = %d;" % model.k_max)
    w("static const uint8_t kPlaneDDot = %d;" % planes.D_DOT)
    w("static const uint8_t kPlaneD1x = %d;" % planes.D_1X)
    w("static const uint8_t kPlaneYLimit = %d;" % planes.Y_LIMIT)
    w("// Hysteresis, as the integer forms of lib/planes.py's comparisons against")
    w("// %.2f of each limit: demote at or below, hold while above." % h)
    w("static const uint8_t kPlaneDDotDown = %d;" % floor_of(h * planes.D_DOT))
    w("static const uint8_t kPlaneD1xDown = %d;" % floor_of(h * planes.D_1X))
    w("static const uint8_t kPlaneYHold = %d;" % floor_of(h * planes.Y_LIMIT))
    w("static const uint8_t kPlaneColsHold[3] = {0, %d, %d};  // by xs" % (
        floor_of(h * 1 * (planes.COLS - 1)), floor_of(h * 2 * (planes.COLS - 1))))
    w("static const uint8_t kPlaneRowsHold[3] = {0, %d, %d};  // by ys" % (
        floor_of(h * 1 * (planes.ROWS - 1)), floor_of(h * 2 * (planes.ROWS - 1))))
    w("")
    w("// 65536 / dy for every edge height; entries 0 to 2 are never read (dy 1")
    w("// and 2 are shifts, and 32768 would not fit a signed multiplier).")
    w("static const uint16_t kPlaneRecip[%d] = {%s};" % (
        len(planes.RECIP), ", ".join(str(v if i > 2 else 0) for i, v in enumerate(planes.RECIP))))
    w("")
    w("#endif")
    with open(DEF_PATH, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", os.path.relpath(DEF_PATH, ROOT))


def write_proj(model):
    """The projection's fixed part as straight-line code. A loop over tables
    of references did the same adds and multiplies, and spent more cycles
    finding its operands and testing their signs than on the arithmetic.

    The magnitudes times k stay a loop over kPlaneMags: planes.cc keeps them
    while k holds, and written out they saved ~300 cycles of 4,300 -- the
    multiplies are the cost -- for ~450 bytes."""
    _, pairs, verts, starts, _, _, _ = model_tables(model)
    out = []
    w = out.append
    w("// Generated by tools/generate_planes.py from lib/planes.py -- do not edit.")
    w("// Regenerate with `make planes` after changing the reference.")
    w("//")
    w("// The projection of the model's fixed part, as straight-line code: every")
    w("// (axis, magnitude) product, and the wing, tailplane and fin vertices as sums")
    w("// of those. c64o/planes.cc includes it after the arrays it reads and writes.")
    w("#ifndef PLANEPROJ_H")
    w("#define PLANEPROJ_H")
    w("")
    names = ("front", "left", "up")
    used = sorted({a for a, _ in pairs})
    w("// _ox[p], _oy[p]: pair p - 1's screen offset, its axis's screen components")
    w("// times its magnitude. Index 0 is the zero product.")
    w("static void _project_pairs(const mat3_t *axes) {")
    for a in used:
        n = names[a]
        w("  int16_t %sy = axes->%s.y, %sz = axes->%s.z;" % (n[0], n, n[0], n))
    for p, (a, m) in enumerate(pairs):
        n = names[a][0]
        w("  _ox[%d] = vec_fastmul8p8(%sy, _px[%d]);" % (p + 1, n, m))
        w("  _oy[%d] = vec_fastmul8p8(%sz, _px[%d]);" % (p + 1, n, m))
    w("}")
    w("")

    def total(axis, refs):
        s = "_c%s" % axis
        for r in refs:
            if r > 0:
                s += " - _o%s[%d]" % (axis, r)
            elif r < 0:
                s += " + _o%s[%d]" % (axis, -r)
        return s

    w("// The flat surfaces: the centre less each coordinate's product.")
    w("static void _project_flat(void) {")
    parts = ("wing", "tailplane", "fin")
    seen = {}
    for i, refs in enumerate(verts):
        if i in starts[:-1]:
            w("  // %s" % parts[starts.index(i)])
        if refs in seen:
            j = seen[refs]
            w("  _vx[%d] = _vx[%d];" % (i, j))
            w("  _vy[%d] = _vy[%d];" % (i, j))
            continue
        seen[refs] = i
        w("  _vx[%d] = (int16_t)(%s);" % (i, total("x", refs)))
        w("  _vy[%d] = (int16_t)(%s);" % (i, total("y", refs)))
    for i, start in enumerate(starts):
        w("  _poly_start[%d] = %d;" % (i, start))
    w("  _poly_count = %d;" % (len(starts) - 1))
    w("  _vert_count = %d;" % len(verts))
    w("}")
    w("")
    w("#endif")
    with open(PROJ_PATH, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", os.path.relpath(PROJ_PATH, ROOT))


def camera_inputs(cam, target, rel_pos_m):
    """The first steps of lib/planes.py render(): what the C64 would hold."""
    pu = tuple(jround(c / planes.RENDER_UNIT_M) for c in rel_pos_m)
    c = tuple(jround(v) for v in to_cam(cam, pu))
    axes = [q88(to_cam(cam, v)) for v in (target.front, target.left, target.up)]
    return c, axes


def signature(r):
    """lib/planes.py's signature without the cycle estimate, which the C
    renderer does not keep."""
    if not r.visible:
        return "invisible:" + r.reason
    blocks = "".join(b.hex() for b in r.buf.blocks)
    return "%d|%d|%dx%d|%d,%d|%d|%d|%s" % (
        r.tier.level, r.tier.ys, r.tier.cols, r.tier.rows,
        r.origin[0], r.origin[1], r.slid, int(r.clamped), blocks)


def drift(elevations, bearings):
    """Positions for a stateful run at one distance: the bearing steps across
    the screen and back on each elevation in turn, down through the sprite
    cut, and each row starts with a frame held twice. With the attitude held
    too, frames in a row mostly share the perspective scale -- the same
    silhouette at another place, sometimes slid -- which is what lets
    planes.cc skip the projection."""
    path = []
    for el in elevations:
        row = list(bearings) + list(reversed(bearings))
        path.extend([(row[0], el)] + [(be, el) for be in row])
    return path


def write_cases(path):
    level = orient(0, 0, 0)
    rows = []
    # Stateless: each case on a fresh state.
    for d in (18, 30, 55, 80, 110, 150, 210, 300, 600, 1100):
        for h in range(-180, 180, 45):
            for b in (0, 30, 60, 89, -45):
                for p in (-30, 0, 30):
                    for be, el in ((0, 0), (8, 4), (-12, -9)):
                        cam, tgt, pos = level, orient(h, p, b), place(d, be, el)
                        r = render(State(), cam, tgt, pos)
                        rows.append((1,) + camera_inputs(cam, tgt, pos) + (
                            signature(r), r.cached))
    # Stateful: approaches through the hysteresis and the cache.
    for cam in (level, orient(0, 5, 15)):
        state = State()
        for i, d in enumerate(range(1500, 19, -7)):
            tgt, pos = orient(150 + i, 5, 25), place(d, 3, -2)
            r = render(state, cam, tgt, pos)
            rows.append((1 if i == 0 else 0,) + camera_inputs(cam, tgt, pos) + (
                signature(r), r.cached))
    # Stateful: drifts that hold distance and attitude.
    bearings = [x * 0.5 for x in range(-4, 5)]
    for tgt in (orient(150, 5, 25), orient(60, -20, 89), orient(20, 25, -30)):
        for d in (45, 80, 150, 400):
            state = State()
            for i, (be, el) in enumerate(drift(range(0, -16, -2), bearings)):
                pos = place(d, be, el)
                r = render(state, level, tgt, pos)
                rows.append((1 if i == 0 else 0,) + camera_inputs(level, tgt, pos) + (
                    signature(r), r.cached))
    out = []
    w = out.append
    w("// Generated by tools/generate_planes.py from lib/planes.py -- do not edit.")
    w("#ifndef PLANES_CASES_H")
    w("#define PLANES_CASES_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w("// lib/planes.py's viewport: centre and the two sprite DMA cuts.")
    w("static const int16_t kCaseCx0 = %d, kCaseCy0 = %d;" % (planes.CX0, planes.CY0))
    w("static const int16_t kCaseCut1 = %d, kCaseCut2 = %d;" % (
        planes.SPRITE_START_MAX, planes.SPRITE_START_MAX_EXP_Y))
    w("")
    w("struct plane_case_t {")
    w("  uint8_t fresh;            // start from a new state")
    w("  int16_t c[3];             // camera space, quarter metres")
    w("  int16_t axes[3][3];       // front, left, up in camera space, 8.8")
    w("  uint32_t hash;            // FNV-1a of the reference's signature")
    w("  uint8_t cached;           // the reference's vertex cache hit")
    w("};")
    w("")
    w("static const plane_case_t kPlaneCases[] = {")
    for fresh, c, axes, sig, cached in rows:
        w("    {%d, {%d, %d, %d}, {{%d, %d, %d}, {%d, %d, %d}, {%d, %d, %d}}, 0x%08xu, %d}," % (
            (fresh,) + c + tuple(axes[0]) + tuple(axes[1]) + tuple(axes[2]) +
            (fnv1a(sig), int(cached))))
    w("};")
    w("")
    w("#endif")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path, "(%d cases)" % len(rows))


def write_target_cases(path):
    """A few dozen cases for c64o/test/target_test.cc, with every expected
    byte spelled out rather than hashed: a 6510 can compare bytes far faster
    than it can compute FNV-1a, and a failure then names the byte.

    The host test already holds planes.cc to lib/planes.py over four thousand
    cases. This exists because oscar64 is not g++: the first version of
    planes.cc passed the host test and drew only the left edge of every
    polygon on the C64."""
    level = orient(0, 0, 0)
    cases = []
    for d in (30, 60, 110, 200, 400, 1100):
        for h, p, b in ((180, 0, 0), (145, 0, 20), (90, 0, 0), (110, 10, 45),
                        (60, -20, 89), (20, 25, -30)):
            cases.append((1, level, orient(h, p, b), place(d, 4, 2)))
    # One stateful run through the hysteresis and the vertex cache.
    for i, d in enumerate(range(130, 50, -8)):
        cases.append((1 if i == 0 else 0, level, orient(150, 5, 25 + (i // 3) * 5), place(d, 3, -2)))
    # And a drift at the size cap, where the scale holds while the slide does
    # not.
    for i, (be, el) in enumerate(drift((-4, -8), (0, 0.5, 1))):
        cases.append((1 if i == 0 else 0, level, orient(150, 5, 25), place(45, be, el)))

    rows, data = [], []
    state = State()
    for fresh, cam, tgt, pos in cases:
        if fresh:
            state = State()
        c, axes = camera_inputs(cam, tgt, pos)
        r = render(state, cam, tgt, pos)
        hidden = {True: 0}.get(r.visible, {"behind camera": 1, "out of range": 2,
                                            "below the sprite cut": 3}.get(r.reason, 9))
        offset = len(data)
        if r.visible:
            for b in r.buf.blocks:
                data.extend(b)
        t = r.tier if r.visible else None
        rows.append((fresh, c, axes, hidden,
                     t.level if t else 0, t.ys if t else 0, t.cols if t else 0,
                     t.rows if t else 0, r.origin[0], r.origin[1], r.slid,
                     int(r.clamped), int(r.cached), offset))
    out = []
    w = out.append
    w("// Generated by tools/generate_planes.py --target from lib/planes.py -- do not edit.")
    w("#ifndef PLANES_TARGET_CASES_H")
    w("#define PLANES_TARGET_CASES_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w("static const int16_t kTargetCx0 = %d, kTargetCy0 = %d;" % (planes.CX0, planes.CY0))
    w("static const int16_t kTargetCut1 = %d, kTargetCut2 = %d;" % (
        planes.SPRITE_START_MAX, planes.SPRITE_START_MAX_EXP_Y))
    w("")
    w("struct plane_target_case_t {")
    w("  uint8_t fresh;")
    w("  int16_t c[3];")
    w("  int16_t axes[3][3];")
    w("  uint8_t hidden, level, ys, cols, rows;")
    w("  int16_t x, y;")
    w("  uint8_t slid, clamped, cached;")
    w("  uint16_t bytes;           // offset into kPlaneTargetBytes")
    w("};")
    w("")
    w("static const uint8_t kPlaneTargetCount = %d;" % len(rows))
    w("static const plane_target_case_t kPlaneTargetCases[%d] = {" % len(rows))
    for (fresh, c, axes, hidden, lv, ys, cols, nrows, x, y, slid, clamped, cached, offset) in rows:
        w("    {%d, {%d, %d, %d}, {{%d, %d, %d}, {%d, %d, %d}, {%d, %d, %d}}, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d}," % (
            (fresh,) + tuple(c) + tuple(axes[0]) + tuple(axes[1]) + tuple(axes[2]) +
            (hidden, lv, ys, cols, nrows, x, y, slid, clamped, cached, offset)))
    w("};")
    w("")
    w("static const uint8_t kPlaneTargetBytes[%d] = {" % len(data))
    for i in range(0, len(data), 21):
        w("    " + ", ".join(str(v) for v in data[i:i + 21]) + ",")
    w("};")
    w("")
    w("#endif")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path, "(%d cases, %d bytes)" % (len(rows), len(data)))


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == "--cases":
        write_cases(sys.argv[2])
    elif len(sys.argv) == 3 and sys.argv[1] == "--target":
        write_target_cases(sys.argv[2])
    elif len(sys.argv) == 1:
        write_def(Model())
        write_proj(Model())
    else:
        sys.exit(__doc__)
